"""
Configuration settings for Track Attendance application.

This is an EXAMPLE file showing all available settings.

IMPORTANT:
1. Do NOT edit this file directly
2. Create a .env file by copying .env.example
3. Fill in your actual values in .env
4. The app will load from .env automatically

If you need to override specific settings in Python, create a local config.py
and edit it (make sure .gitignore includes any config files with secrets).
"""

# =============================================================================
# Cloud API Configuration (REQUIRED)
# =============================================================================
# Load from environment or .env file
# If not set, app will fail at startup with clear error message

# Production Cloud Run API endpoint
CLOUD_API_URL = "https://trackattendance-api-969370105809.asia-southeast1.run.app"

# API authentication key - LOAD FROM ENVIRONMENT
# NEVER commit real API keys to git
# Set via: export CLOUD_API_KEY="your-key" or in .env file
CLOUD_API_KEY = "your-api-key-here"  # Load from env in production


# =============================================================================
# Auto-Sync Configuration
# =============================================================================

# Enable/disable automatic synchronization
AUTO_SYNC_ENABLED = True

# Time in seconds to wait after last scan before allowing auto-sync
# This ensures auto-sync only happens during idle periods
AUTO_SYNC_IDLE_SECONDS = 30

# Interval in seconds to check if auto-sync should run
# Auto-sync will check every N seconds if conditions are met
AUTO_SYNC_CHECK_INTERVAL_SECONDS = 60

# Minimum number of pending scans required to trigger auto-sync
# Set to 1 to sync as soon as any scan is pending
AUTO_SYNC_MIN_PENDING_SCANS = 1

# Show status message when auto-sync starts
AUTO_SYNC_SHOW_START_MESSAGE = True

# Show status message when auto-sync completes
AUTO_SYNC_SHOW_COMPLETE_MESSAGE = True

# Duration in milliseconds to show auto-sync messages
AUTO_SYNC_MESSAGE_DURATION_MS = 3000

# Network connection timeout in seconds for connectivity checks
AUTO_SYNC_CONNECTION_TIMEOUT = 5


# =============================================================================
# Sync Resilience Configuration
# =============================================================================

# Retry failed sync operations with exponential backoff
SYNC_RETRY_ENABLED = True
SYNC_RETRY_MAX_ATTEMPTS = 3
SYNC_RETRY_BACKOFF_SECONDS = 5  # Initial backoff (doubles each attempt)

# Auto-sync failure handling
AUTO_SYNC_MAX_CONSECUTIVE_FAILURES = 5  # Cool-down after N failures
AUTO_SYNC_FAILURE_COOLDOWN_SECONDS = 300  # 5 minutes


# =============================================================================
# Roster Validation Configuration
# =============================================================================

# Expected column headers in employee.xlsx
REQUIRED_ROSTER_COLUMNS = [
    "Legacy ID",
    "Full Name",
    "SL L1 Desc",
    "Position Desc"
]

# Show warning if roster is missing or invalid
ROSTER_VALIDATION_ENABLED = True

# Skip import if any required columns are missing
ROSTER_STRICT_VALIDATION = True


# =============================================================================
# Logging Configuration
# =============================================================================

# File logging for diagnostics
LOGGING_ENABLED = True
LOGGING_FILE = "logs/trackattendance.log"
LOGGING_LEVEL = "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Also log to console
LOGGING_CONSOLE = True

# Log sensitive data (API keys, etc) - NEVER in production
LOG_SECRETS = False


# =============================================================================
# Application Paths
# =============================================================================

DATA_DIRECTORY_NAME = "data"
EXPORT_DIRECTORY_NAME = "exports"
DATABASE_FILENAME = "database.db"
EMPLOYEE_WORKBOOK_FILENAME = "employee.xlsx"


# =============================================================================
# UI Configuration
# =============================================================================

# Window behavior
SHOW_FULL_SCREEN = True
ENABLE_FADE_ANIMATION = True

# Export behavior
AUTO_EXPORT_ON_SHUTDOWN = True


# =============================================================================
# Cloud Sync Batch Configuration
# =============================================================================

# Number of scans to sync in each batch
CLOUD_SYNC_BATCH_SIZE = 100
